version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: db
    env_file:
      - .env.local
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    depends_on:
      - db
      - media_service

  media_service:
    build:
      context: .
      dockerfile: Dockerfile.media_service
    container_name: media_service
    env_file:
      - .env.local
    ports:
      - "8001:8001"
    depends_on:
      - minio

  minio:
    image: minio/minio
    container_name: minio
    env_file:
      - .env.local
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data: